"""Alert History: reads real alert records produced by the Phase 5 alert
engine (alerts/run_alerts.py). This view is strictly read-only - it never
evaluates conditions or sends anything itself, so simply opening or
refreshing the dashboard can never trigger a Discord message.
"""
import streamlit as st

from config.settings import WATCHLIST
from dashboard import components
from dashboard.data import get_alert_history, get_price_alert_history, get_run_history


def _status_label(row) -> str:
    if row["dry_run"]:
        return "Dry-run (not sent)"
    if row["delivered"]:
        return "Delivered"
    if row["delivery_error"]:
        return f"Failed: {row['delivery_error']}"
    return "Pending"


def render():
    st.title("Alert History")
    st.caption(
        "A local log of signal-score alerts generated by the alert engine (`python -m alerts.run_alerts`). "
        "Dry-run alerts are recorded here but never sent to Discord; real delivery requires the explicit `--send` flag."
    )

    ticker_filter = st.selectbox("Filter by ticker", ["All"] + WATCHLIST)

    alerts = get_alert_history(limit=200)
    if ticker_filter != "All":
        alerts = alerts[alerts["ticker"] == ticker_filter]

    if alerts.empty:
        components.empty_state(
            "No alerts recorded yet",
            "This view reads real alert records from the local database. None exist yet for this filter — "
            "run `python -m alerts.run_alerts` (or `python -m automation.run_daily`) to evaluate the watchlist "
            "(dry-run by default, never contacts Discord). Note the first evaluation of any ticker only "
            "establishes a baseline and won't itself produce an alert.",
            icon="🔔",
        )
    else:
        display = alerts.copy()
        display["Status"] = display.apply(_status_label, axis=1)
        display["Score"] = display.apply(
            lambda r: f"{r['score']:.0f}" + (f" (was {r['previous_score']:.0f})" if r["previous_score"] is not None else ""),
            axis=1,
        )
        display["Stage"] = display.apply(
            lambda r: f"{r['highest_confirmed_stage']}" + (f" (was {r['previous_stage']})" if r["previous_stage"] else ""),
            axis=1,
        )
        display["As of"] = display.apply(
            lambda r: f"{r['data_date']} ({r['source']})" if r["data_date"] else "n/a", axis=1,
        )

        display = display.rename(columns={
            "ticker": "Ticker", "triggered_at": "Triggered at", "alert_type": "Reason", "message": "Message",
        })
        columns = ["Ticker", "Triggered at", "Reason", "Score", "Stage", "As of", "Status", "Message"]
        st.dataframe(display[columns], use_container_width=True, hide_index=True)

    st.divider()
    _render_price_alert_history()

    st.divider()
    _render_run_history()


def _channel_status(delivered, error) -> str:
    if delivered:
        return "delivered"
    if error:
        return f"failed ({error})"
    return "pending"


def _price_status_label(row) -> str:
    if row["dry_run"]:
        return "Dry-run (not sent)"
    email_status = _channel_status(row["delivered"], row["delivery_error"])
    discord_status = _channel_status(row["discord_delivered"], row["discord_delivery_error"])
    return f"Email: {email_status} | Discord: {discord_status}"


def _render_price_alert_history():
    st.subheader("Price-threshold alert history")
    st.caption(
        "A local log of price-threshold alerts generated by the price-alert engine "
        "(`python -m alerts.run_price_alerts`, or the daily automation pipeline). "
        "Dry-run alerts are recorded here but never emailed or posted to Discord; real delivery "
        "requires the explicit `--send` flag, and each channel is attempted and tracked independently."
    )

    price_alerts = get_price_alert_history(limit=200)
    if price_alerts.empty:
        st.caption(
            "No price-threshold alerts recorded yet. Configure thresholds on the Price Alert Thresholds page and run "
            "`python -m alerts.run_price_alerts` (dry-run by default) to evaluate them."
        )
        return

    display = price_alerts.copy()
    display["Status"] = display.apply(_price_status_label, axis=1)
    display["Direction"] = display["alert_type"].map({"price_above": "Above", "price_below": "Below"}).fillna(display["alert_type"])
    display["Price"] = display.apply(
        lambda r: f"${r['price']:,.2f}" + (f" (was ${r['previous_price']:,.2f})" if r["previous_price"] is not None else ""),
        axis=1,
    )
    display["Threshold"] = display["threshold"].apply(lambda v: f"${v:,.2f}")
    display["As of"] = display.apply(
        lambda r: f"{r['data_date']} ({r['source']})" if r["data_date"] else "n/a", axis=1,
    )
    display = display.rename(columns={"ticker": "Ticker", "triggered_at": "Triggered at", "message": "Message"})
    columns = ["Ticker", "Triggered at", "Direction", "Price", "Threshold", "As of", "Status", "Message"]
    st.dataframe(display[columns], use_container_width=True, hide_index=True)


def _render_run_history():
    st.subheader("Automation run history")
    st.caption(
        "Recent runs of the scheduled pipeline (`python -m automation.run_daily`). This dashboard only reads "
        "this table — it never runs the pipeline itself."
    )

    runs = get_run_history(limit=20)
    if runs.empty:
        st.caption("No automation runs recorded yet.")
        return

    display = runs.copy()
    display = display.rename(columns={
        "started_at": "Started", "finished_at": "Finished", "status": "Status", "send_mode": "Mode",
        "tickers_attempted": "Attempted", "tickers_updated": "Updated", "tickers_failed": "Failed",
        "alerts_generated": "Alerts", "error_summary": "Errors",
    })
    columns = ["Started", "Finished", "Status", "Mode", "Attempted", "Updated", "Failed", "Alerts", "Errors"]
    st.dataframe(display[columns], use_container_width=True, hide_index=True)
